# Generated by Django 4.2.18 on 2025-02-01 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tickets_closed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tickets_in_progress',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tickets_pending',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(help_text='The user associated with this profile.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
