# Generated by Django 4.2.18 on 2025-01-27 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], db_index=True, default='READY', help_text='The current status of the email.', max_length=255)),
                ('from_email', models.EmailField(help_text='The email address of the sender.', max_length=254)),
                ('to_email', models.EmailField(help_text='The email address of the recipient.', max_length=254)),
                ('subject', models.CharField(help_text='The subject of the email.', max_length=255)),
                ('message', models.TextField(help_text='The plain-text body of the email.')),
                ('html', models.TextField(help_text='The HTML content of the email (optional).')),
                ('sent_at', models.DateTimeField(blank=True, help_text='The timestamp when the email was sent (if applicable).', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
